### ISSUE TITLE
Wrong favicon on Safari

### ISSUE THREAD

**Issue by ThisIsIPat** [TaecGmbH/taec.de#5]
Though 3 PRs attempted to fix this, there is still a white border around the favicon on iOS devices and on the Safari browser:

https://github.com/TaecGmbH/taec.de/pull/4 attempted to fix this, but unsuccessfully.

Upon further research, these links could be helpful:
https://www.reddit.com/r/vivaldibrowser/comments/ipj1j4/active_tab_favicon_white_outline_on_dark_theme/
https://paco.me/writing/safari-favicon-showing-white-background

It is likely Apple determines the icon too dark. A replacement favicon with lighter brown colors is suggested to fix this.

**Comment by tor-inge** [comment]
The favicon looks fine for me om my phone, but I have not tested on Safari on desktop.

OS: iOS 17.2.1 (21C66)

![image](https://github.com/TaecGmbH/taec.de/assets/43708528/8a932d40-55c8-4f3e-829d-a1c0e8fea296)

**Comment by ThisIsIPat** [comment]
Will be closed with https://github.com/team-inprop/taec.de/issues/17

**Comment by ThisIsIPat** [comment]
Closed due to irrelevance after #17
