### ISSUE TITLE
Add logos of scholarship suppliers

### ISSUE THREAD

**Issue by ThisIsIPat** [TaecGmbH/taec.de#9]
As per requirement of the scholarship partners, their logos need to be displayed:

###  EU Financing logo ("Cofinanced by the European Union")
![eu-funding-logo](https://github.com/TaecGmbH/taec.de/assets/10747604/c97ea4d5-3ea3-406c-adc7-8dc03037e726)

### Berlin logo (The city of Berlin)
![berlin_logo](https://github.com/TaecGmbH/taec.de/assets/10747604/fcee23ff-3e20-4de6-b4fb-4fe7ee1e7e41)

### Science and Startups logo (A co-initiative of 4 universities in Berlin)
![Science-Startups-Logo_3840px-lang](https://github.com/TaecGmbH/taec.de/assets/10747604/90eb5a32-5596-468c-bc0a-c5226cf502c0)

### Technical University of Berlin logo (The mediator for the scholarship)
![TU-Berlin-Logo](https://github.com/TaecGmbH/taec.de/assets/10747604/8d10958c-826e-448d-a6a8-cf8cc69fadf8)

**Comment by ThisIsIPat** [comment]
The logos need to be equally large, best on an overlay

**Comment by tor-inge** [comment]
Are they to be added in the footer of all pages, or just in the impressum? @ThisIsIPat

**Comment by ThisIsIPat** [comment]
Needs to be on the main page (!), but footer should be fine. Doesn't need to be small, should be about 2/3 of a row wide at least. If you think it fits in the design, you could consider it as an overlay for the header background image

**Comment by ThisIsIPat** [comment]
If it's in the footer, add it to all pages. honestly, footer is probably the best place either way
